public class ProductRequestWrapper {
    public String materialNumber;
    public String articleName;
    public Integer preferredQuantity;
    public String application;
    public String machineType;
    public String serialNumber;
    public Integer shaftDiameter;
    public Integer rotationSpeed;
    public String machineTag;
    public Integer pressure;
    public Integer temperature;
    public String medium;
    public String abrasiveParticles;
    public String productCategory;
    public String sealingSupplySystemInput;
    public String planInput; 
    public String operatingLocationInput;
    public String additionalInfoInput;
    public List<String> selectedCertificates; // Multiselect Picklist
    public String applicationInput;
    public String dimensionsSealChamberInput; 
    public Integer movementRPMInput; 
    public String geometryInput; 
    public String screwsInput; 
    public String othersInput;
    public String title;
    public String firstName;
    public String lastName;
    public String email;
    public String phoneNumber;
    public String customerNumber;
    public String msgInput;
}
